name: Deploy to Railway

on:
  push:
    branches: [ main ]

jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Imprimir en consola
        run: echo "Hello World, GITHUB ACTIONS"

  test:
    needs: helloworld
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Firebase credentials file
        run: |
          mkdir -p secrets
          echo "${{ secrets.FIREBASE_CREDENTIALS_BASE64 }}" | base64 --decode > secrets/inklink-firebase-adminsdk.json

      - name: Test FastAPI imports
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_CREDENTIALS_BASE64: ${{ secrets.FIREBASE_CREDENTIALS_BASE64 }}
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          python -c "from main import app; print('FASTAPI app imported successfully')"

      - name: Run tests
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_CREDENTIALS_BASE64: ${{ secrets.FIREBASE_CREDENTIALS_BASE64 }}
        run: |
          python -m pytest -v test_database.py
