name: Deploy to Railway

on:
  push: 
    branches:
      - main
      
jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Imprimir en consola
        run: echo "Hola, mundo"
  
  test:
    needs: helloworld
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test FastAPI imports
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          FIREBASE_CREDENTIALS_BASE64: ${{ secrets.FIREBASE_CREDENTIALS_BASE64 }}
        run: |
          pytest -v test_database.py
